set.seed(1)
x <- c(rt(200, df = 2), rt(200, df = 2, ncp = 5))
result_mean <- detect_mean(x)
summary(result_mean)
result_rank <- detect_rank(x)
summary(result_rank)
rank_profile <- confint(result_rank, method = "profile", window = 2)
rank_wald <- confint(result_rank, parm = "theta", method = "wald")
