#!/usr/bin/env python3
"""Generate deterministic CSV data shared by the language test suites."""

import argparse
import csv
from pathlib import Path


FIXTURE_DIR = Path(__file__).resolve().parent
MANIFEST_PATH = FIXTURE_DIR / "manifest.tsv"


def _csv(header, rows):
    """Render a CSV with stable Unix newlines and a final newline."""
    return header + "\n" + "\n".join(rows) + "\n"


def _numbers(values):
    """Render the compact decimal spelling used by the fixture CSVs."""
    return [f"{value:g}" for value in values]


def _lm_rows():
    """Create a slope change with a fixed, repeating error cycle."""
    errors = (0.2, -0.4, 0.7, -0.1, 0.5, -0.8, 0.3)
    rows = []
    for x in range(1, 41):
        slope = 2 if x <= 20 else -1
        y = slope * x + errors[(x - 1) % len(errors)]
        rows.append(f"{y:g},{x}")
    return rows


def _var_rows():
    """Create two deterministic bivariate VAR regimes."""
    first_cycle = ((1, 0), (0, 1), (-1, 0), (0, -1))
    second_cycle = ((5, 1), (1, 5), (-5, -1), (-1, -5))
    return [
        f"{first:g},{second:g}"
        for first, second in first_cycle * 10 + second_cycle * 10
    ]


def _arima_values():
    """Integrate fixed small then large alternating increments."""
    increments = [0.1, -0.1] * 20 + [2.0, -2.0] * 20 + [2.0]
    values = [0.0]
    for increment in increments:
        values.append(values[-1] + increment)
    return values


def _arma_values():
    """Create the fixed AR(1) input used by the ARMA variance estimator."""
    innovations = (1.2, -0.7, 0.3, 2.1, -1.4, 0.8, -2.2, 0.5, 0.1, -0.9)
    values = [0.0] * 80
    for index in range(1, len(values)):
        values[index] = 0.65 * values[index - 1] + innovations[
            index % len(innovations)
        ]
    return values


def rendered_fixture_data():
    """Return every generated CSV as an exact UTF-8 text payload."""
    return {
        "mean_step.csv": _csv("value", _numbers([0] * 20 + [5] * 20)),
        "variance_step.csv": _csv(
            "value", _numbers([1, -1] * 20 + [5, -5] * 20)
        ),
        "meanvariance_step.csv": _csv(
            "value", _numbers([0, 1, -1, 0] * 10 + [5, 8, 2, 5] * 10)
        ),
        "exponential_step.csv": _csv(
            "value", _numbers([1, 2, 3, 4] * 10 + [10, 20, 30, 40] * 10)
        ),
        "lm_step.csv": _csv("y,x", _lm_rows()),
        "var_step.csv": _csv("y1,y2", _var_rows()),
        "rank_step.csv": _csv(
            "value", _numbers([0, 1, 2, 3] * 5 + [100, 101, 102, 103] * 5)
        ),
        "arima_increment.csv": _csv("value", _numbers(_arima_values())),
        "arma_variance.csv": _csv(
            "value", [f"{value:.6f}" for value in _arma_values()]
        ),
    }


def manifest_data_files():
    """Return the CSV files named by the authoritative fixture manifest."""
    with MANIFEST_PATH.open(newline="", encoding="utf-8") as stream:
        return {row["data_file"] for row in csv.DictReader(stream, delimiter="\t")}


def _validate_file_index(payloads):
    generated = set(payloads)
    listed = manifest_data_files()
    if generated != listed:
        missing = sorted(generated - listed)
        extra = sorted(listed - generated)
        details = []
        if missing:
            details.append("missing from manifest: " + ", ".join(missing))
        if extra:
            details.append("not generated: " + ", ".join(extra))
        raise ValueError("Fixture manifest mismatch (" + "; ".join(details) + ")")


def _check(output_dir):
    payloads = rendered_fixture_data()
    _validate_file_index(payloads)
    stale = []
    for filename, expected in payloads.items():
        path = output_dir / filename
        if not path.exists() or path.read_bytes() != expected.encode("utf-8"):
            stale.append(filename)
    stale.extend(
        path.name for path in output_dir.glob("*.csv") if path.name not in payloads
    )
    if stale:
        print("Out-of-date shared fixtures: " + ", ".join(sorted(stale)))
        return 1
    print("Shared fixtures are up to date.")
    return 0


def _write(output_dir):
    payloads = rendered_fixture_data()
    _validate_file_index(payloads)
    output_dir.mkdir(parents=True, exist_ok=True)
    for filename, content in payloads.items():
        (output_dir / filename).write_bytes(content.encode("utf-8"))
    print(f"Wrote {len(payloads)} shared CSV files to {output_dir}")
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed fixtures differ from generated bytes",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=FIXTURE_DIR,
        help=(
            "fixture directory to check or regenerate "
            "(default: script directory)"
        ),
    )
    arguments = parser.parse_args()
    if arguments.check:
        return _check(arguments.output_dir)
    return _write(arguments.output_dir)


if __name__ == "__main__":
    raise SystemExit(main())
