# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function to calculate the gradient at the current data.
#'
#' @param data A data frame containing the data to be segmented.
#' @param theta Estimated theta from the previous iteration.
#' @param family Family of the model.
#'
#' @return Gradient at the current data.
#' @export
cost_update_gradient <- function(data, theta, family) {
    .Call(`_fastcpd_cost_update_gradient`, data, theta, family)
}

#' Function to calculate the Hessian matrix at the current data.
#'
#' @param data A data frame containing the data to be segmented.
#' @param theta Estimated theta from the previous iteration.
#' @param family Family of the model.
#' @param min_prob Minimum probability to avoid numerical issues.
#'
#' @return Hessian at the current data.
#' @export
cost_update_hessian <- function(data, theta, family, min_prob) {
    .Call(`_fastcpd_cost_update_hessian`, data, theta, family, min_prob)
}

