# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Update the cost values for the segmentation.
#'
#' @param data A data frame containing the data to be segmented.
#' @param theta_hat Estimated theta from the previous iteration.
#' @param theta_sum Sum of estimated theta from the previous iteration.
#' @param hessian Hessian matrix from the previous iteration.
#' @param tau Start of the current segment.
#' @param i Index of the current data in the whole data set.
#' @param k Number of epochs in SGD.
#' @param family Family of the model.
#' @param momentum Momentum from the previous iteration.
#' @param momentum_coef Momentum coefficient to be applied to the current
#'   momentum.
#' @param epsilon Epsilon to avoid numerical issues. Only used for binomial and
#'   poisson.
#' @param min_prob Minimum probability to avoid numerical issues. Only used for
#'   poisson.
#' @param winsorise_minval Minimum value to be winsorised. Only used for
#'   poisson.
#' @param winsorise_maxval Maximum value to be winsorised. Only used for
#'   poisson.
#' @param lambda Lambda for L1 regularization. Only used for lasso.
#' @param cost_gradient Gradient for custom cost function.
#' @param cost_hessian Hessian for custom cost function.
#'
#' @return A list containing new values of \code{theta_hat}, \code{theta_sum},
#'   \code{hessian}, and \code{momentum}.
cost_update_c <- function(data, theta_hat, theta_sum, hessian, tau, i, k, family, momentum, momentum_coef, epsilon, min_prob, winsorise_minval, winsorise_maxval, lambda, cost_gradient, cost_hessian) {
    .Call(`_fastcpd_cost_update_c`, data, theta_hat, theta_sum, hessian, tau, i, k, family, momentum, momentum_coef, epsilon, min_prob, winsorise_minval, winsorise_maxval, lambda, cost_gradient, cost_hessian)
}

#' Function to calculate the gradient at the current data.
#'
#' @param data A data frame containing the data to be segmented.
#' @param theta Estimated theta from the previous iteration.
#' @param family Family of the model.
#'
#' @return Gradient at the current data.
cost_update_gradient <- function(data, theta, family) {
    .Call(`_fastcpd_cost_update_gradient`, data, theta, family)
}

#' Function to calculate the Hessian matrix at the current data.
#'
#' @param data A data frame containing the data to be segmented.
#' @param theta Estimated theta from the previous iteration.
#' @param family Family of the model.
#' @param min_prob Minimum probability to avoid numerical issues.
#'
#' @return Hessian at the current data.
cost_update_hessian <- function(data, theta, family, min_prob) {
    .Call(`_fastcpd_cost_update_hessian`, data, theta, family, min_prob)
}

